#ifndef __CONFIG_H__
#define __CONFIG_H__

#ifndef FREQ_SAMPLING_RATE
#define FREQ_SAMPLING_RATE 44100
#endif/*FREQ_SAMPLING_RATE*/

#define FREQ_STEP_COARSE 10
#define FREQ_START 440

#define CYCLES_PER_SYMBOL 4
#define SYMBOL_PAUSE 16
#define FILTER_DEPTH 16

#endif/*__CONFIG_H__*/
